Feature: Registration
	In order to avoid silly mistakes
	As a math idiot
	I want to be told the sum of two numbers

#@Registration
#Scenario Outline: 2 As a user i want to Signup using Debit Card
#	Given the test case title is "<Case>"	
#	And I set value in context from data "<scroll_text>" as "scroll_text"
#	And I set value in context from data "<CNIC_D>" as "customer_cnic"
#	And I set value in context from data "<account_tag1>" as "AccountForTag"
#	And the user is arrive to Internet Banking home page 
#	And I am clicking on "Signup_registerBtn"
#	#And I am performing "OK" alert operation on cross icon on "Signup_CrossIcon"
#	##If you select OK option on above step then repeat Signup_registerBtn clicking step"
#	#And I am clicking on "Signup_registerBtn" 
#	And I am clicking on "Signup_DebitCardNav"
#	#And verify through "<debit_req_text1>" on "Signup_DebitReqText1"
#	#And verify through "<debit_req_text2>" on "Signup_DebitReqText2"
#	And I am clicking on "Signup_Debit_NextBtn"
#	#And I am performing on "Signup_LngTextBtn"
#	#And I verify if text exist on webpage of "Signup_UrduText"
#	#And I am performing on "Signup_LngTextBtn"
#	When I scroll to element "Signup_Scroll"
#	And I am performing on "Signup_AcceptBtn"
#	And verify DVL setting through database on "<dvl_query>" on Schema "DIGITAL_CHANNEL_SEC" with date of birth "<dob>" on keyword "Signup_DOB"
#	And I have given "<CNIC_D>" on "Signup_CNIC"
#	And I have given "<Debit_card_no>" on "Signup_CardNo"
#	And I have given "<pin>" on "Signup_CardPin"
#	And I have given "<Login_id>" on "Signup_LoginId"
#	And I am performing on "Signup_ContinueBtn"
#	#And I count Number of Account on "Signup_AccountCount"
#	And I save Account Numbers
#	#And verify through "<account_tag1>" on "Signup_TagAccountNo"
#	And I am clicking on "Signup_AccountToggle"
#	And I am performing on "Signup_LastRegisterBtn"
#	And verify the message "<account_tag1>" through database on "<account_query>" on Schema "DIGITAL_CHANNEL_SEC"
#	And verify the message "<account_tag1>" through database on "<account_tag_query>" on Schema "DIGITAL_CHANNEL_SEC"
#	And verify through "<Login_id>" on "Signup_LoginIdTextVerf"
#	And verify through "<success_message1>" on "Signup_SuccessMessage1"
#	And verify through "<success_message2>" on "Signup_SuccessMessage2"
#	And verify through "<success_message3>" on "Signup_SuccessMessage3"
#	And I am performing on "Signup_SuccessNextBtn"
#	And verify the result from "<created_on_query>" on Schema "DIGITAL_CHANNEL_SEC"
#	And verify the result from "<updated_on_query>" on Schema "DIGITAL_CHANNEL_SEC"
#	And verify the result from "<last_login_query>" on Schema "DIGITAL_CHANNEL_SEC"
#	And verify the result from "<transaction_password_query>" on Schema "DIGITAL_CHANNEL_SEC"
#	And verify the message "<customer_type>" through database on "<customer_type_query>" on Schema "DIGITAL_CHANNEL_SEC"
#	And verify the result from "<IVR_require_query>" on Schema "DIGITAL_CHANNEL_SEC"
#	And verify the result from "<IVR_check_query>" on Schema "DIGITAL_CHANNEL_SEC"
#	And verify the result from "<PARAM_CHANNEL_ID_query>" on Schema "DIGITAL_CHANNEL_SEC"
#	And verify the result from "<ENABLE_PSD_require_query>" on Schema "<DIGITAL_CHANNEL_SEC>"
#	And verify the result from "<ENABLE_PSD_check_query>" on Schema "<DIGITAL_CHANNEL_SEC>"
#	And update the data by query "<password_query>" on DIGITAL_CHANNEL_SEC
#	Then I have given "<Login_id>" on "Login_UserId"
#	And I have given "<activation_password>" on "Login_Password"
#	And  I am performing on "Login_SignIn_Button"
#	And verify the result from "<password_policy_query>" on Schema "DIGITAL_CHANNEL_SEC"
#	And verify through "Signup_PassPolicy" on "Signup_PassPolicy"
#	Then I have given "<new_password>" on "Signup_ReLoginPassword"
#	And I have given "<new_password>" on "Signup_ReLoginPassword"
#	And I have given "<activation_password>" on "Signup_TransactionPassword"
#	And I have given "<activation_password>" on "Signup_ReTransactionPassword"
#	And I am performing on "Signup_SubmitBtn"
#	And verify through "<success_message>" on "Signup_PaswwordText" 
#	And I am performing on "Signup_PaswwordOkBtn"
#	And verify the result from "<last_login_query>" on Schema "DIGITAL_CHANNEL_SEC"
#	And verify the message "<Login_id>" through database on "<login_id_query>" on Schema "DIGITAL_CHANNEL_SEC"
#	And verify the result from "<transaction_password_query>" on Schema "DIGITAL_CHANNEL_SEC"
#	And verify the result from "<password_change_req_query>" on Schema "DIGITAL_CHANNEL_SEC"
#	Then I have given "<Login_id>" on "Login_UserId"
#	And I have given "<new_password>" on "Login_Password"
#	And  I am performing on "Login_SignIn_Button"
#	And I wait 2000
#	And I am clicking on keyword "Signup_FeedbackOptionHBL" with value "<feedback_type>"
#	And I have given "<feedback_option>" on "Signup_FeedbackText"
#	And I am performing on "Signup_FeedbackSubmit"
#	And verify through "Thank you for letting us know." on "Signup_FeedbackMessage"
#	And I am performing on "Signup_FeedbackOkBtn"
#	Then verify through "Welcome" on "Login_Success_Text"
#
#	@source:Data/DebitRegistration.xlsx
#	Examples:
#	|Case|CNIC_D|Debit_card_no|pin|dob|Login_id|scroll_text|activation_password|password_query|account_tag1|new_password|success_message|account_query|account_tag_query|feedback_type|feedback_option|password_change_req_query|transaction_password_query|success_message1|success_message2|success_message3|debit_req_text1|debit_req_text2|login_id_query|password_policy_query|IVR_require_query|IVR_check_query|dvl_query|customer_type|customer_type_query|created_on_query|updated_on_query|last_login_query|PARAM_CHANNEL_ID_query|ENABLE_PSD_require_query|ENABLE_PSD_check_query|


@Registration
Scenario Outline: As a user i want to Signup using Debit Card Web
	Given the test case title is "<Case>"
	And I set value in context from data "<scroll_text>" as "scroll_text"
	And I set value in context from data "<CNIC_D>" as "customer_cnic"
	And I set value in context from data "True" as "SignupCheck"
	And I set value in context from data "<account_tag1>" as "AccountForTag"
	And the user is arrive to Internet Banking home page 
	And I am clicking on "Registration_registerBtn"
	When I have given "<CNIC_D>" on "Registration_CNIC"
	And I am clicking on "Registration_NextBtn"
	And I scroll to element "Registration_Scroll"
	And I am performing on "Registration_AcceptBtn"
	And I have given "<Debit_card_no>" on "Registration_CardNo"
	And I have given "<pin>" on "Registration_CardPin"
	And I have given "<Login_id>" on "Registration_LoginId"
	And I am performing on "Registration_FormNextBtn"
	And I save Account Numbers
	And I am clicking on "Registration_AccountToggle"
	And I am performing on "Registration_AccNextBtn"
	And I have given "<OTP_Value>" on "Login_OTP_field"
	And I scroll to element "Registration_OtpNextBtn"
	And I am performing on "Registration_OtpNextBtn"
	And I wait 3000
	And verify the message "<account_tag1>" through database on "<account_query>" on Schema "DIGITAL_CHANNEL_SEC"
	And verify the message "<account_tag1>" through database on "<account_tag_query>" on Schema "DIGITAL_CHANNEL_SEC"
	And verify through database on "<password_policy_query>" on Schema "DIGITAL_CHANNEL_SEC" on "Registration_PassPolicyText"
	And I have given "<login_pass>" on "Registration_LoginID"
	And I have given "<login_pass>" on "Registration_ReLoginID"
	And I have given "<tran_pass>" on "Registration_TranPass"
	And I have given "<tran_pass>" on "Registration_ReTranPass"
	And I am performing on "Registration_FinishBtn"
	Then verify through "<success_message>" on "Registration_PaswwordText"
	And I am performing on "Registration_PaswwordOkBtn"
	And verify the message "<Login_id>" through database on "<login_id_query>" on Schema "DIGITAL_CHANNEL_SEC"
	And verify the result from "<created_on_query>" on Schema "DIGITAL_CHANNEL_SEC"
	And verify the result from "<updated_on_query>" on Schema "DIGITAL_CHANNEL_SEC"
	#And verify the result from "<transaction_password_query>" on Schema "DIGITAL_CHANNEL_SEC"
	And verify the message "<customer_type>" through database on "<customer_type_query>" on Schema "DIGITAL_CHANNEL_SEC"
	And verify the result from "<IVR_require_query>" on Schema "DIGITAL_CHANNEL_SEC"
	And verify the result from "<IVR_check_query>" on Schema "DIGITAL_CHANNEL_SEC"
	And verify the result from "<PARAM_CHANNEL_ID_query>" on Schema "DIGITAL_CHANNEL_SEC"
	And verify the result from "<ENABLE_PSD_require_query>" on Schema "DIGITAL_CHANNEL_SEC"
	And verify the result from "<ENABLE_PSD_check_query>" on Schema "DIGITAL_CHANNEL_SEC"
	And I have given "<Login_id>" on "Login_UserId"
	And I have given "<login_pass>" on "Login_Password"
	And  I am performing on "Login_SignIn_Button"
	And I set value in context from data "true" as "Last_login_flag"
	#And I am clicking on keyword "Signup_FeedbackOptionHBL" with value "<feedback_type>"
	#And I have given "<feedback_option>" on "Signup_FeedbackText"
	#And I am performing on "Signup_FeedbackSubmit"
	#And verify through "Thank you for letting us know." on "Signup_FeedbackMessage"
	#And I am performing on "Signup_FeedbackOkBtn"
	And I am clicking on "Signup_SkipBtn"
	And verify through "Welcome" on "Login_Success_Text"
	And verify the result from "<Last_login_query>" on Schema "DIGITAL_CHANNEL_SEC"

@source:Data/DebitRegistration.xlsx
	Examples:
	|Case|CNIC_D|Debit_card_no|pin|Login_id|scroll_text|password_policy_query|login_pass|tran_pass|account_tag1|account_query|account_tag_query|success_message|login_id_query|created_on_query|updated_on_query|Last_login_query|transaction_password_query|customer_type|customer_type_query|IVR_require_query|IVR_check_query|ENABLE_PSD_require_query|ENABLE_PSD_check_query|PARAM_CHANNEL_ID_query|feedback_type|feedback_option|


@Registration
Scenario Outline: As a user i want to Signup using Credit Card Web
	Given the test case title is "<Case>"
	And I set value in context from data "<scroll_text>" as "scroll_text"
	And I set value in context from data "<CNIC_D>" as "customer_cnic"
	And I set value in context from data "True" as "SignupCheck"
	And the user is arrive to Internet Banking home page 
	And I am clicking on "Registration_registerBtn"
	When I have given "<CNIC_D>" on "Registration_CNIC"
	And I am clicking on "Registration_NextBtn"
	And I scroll to element "Registration_Scroll"
	And I am performing on "Registration_AcceptBtn"
	And I have given "<Credit_card_no>" on "Registration_CardNo"
	And I have given "<Customer_Email>" on "Registration_Email"
	And I have given "<Login_id>" on "Registration_LoginId"
	And I am clicking on "Registration_FormNextBtn"
	And I wait 3000
	And I have given "<OTP_Value>" on "Login_OTP_field"
	And I scroll to element "Registration_OtpNextBtn"
	And I am performing on "Registration_OtpNextBtn"
	And verify through database on "<password_policy_query>" on Schema "DIGITAL_CHANNEL_SEC" on "Registration_PassPolicyText"
	And I have given "<login_pass>" on "Registration_LoginID"
	And I have given "<login_pass>" on "Registration_ReLoginID"
	And I have given "<tran_pass>" on "Registration_TranPass"
	And I have given "<tran_pass>" on "Registration_ReTranPass"
	And I am performing on "Registration_FinishBtn"
	Then verify through "<success_message>" on "Registration_PaswwordText"
	And I am performing on "Registration_PaswwordOkBtn"
	And verify the message "<Login_id>" through database on "<login_id_query>" on Schema "DIGITAL_CHANNEL_SEC"
	And verify the result from "<created_on_query>" on Schema "DIGITAL_CHANNEL_SEC"
	And verify the result from "<updated_on_query>" on Schema "DIGITAL_CHANNEL_SEC"
	And verify the message "<customer_type>" through database on "<customer_type_query>" on Schema "DIGITAL_CHANNEL_SEC"
	And verify the result from "<IVR_require_query>" on Schema "DIGITAL_CHANNEL_SEC"
	And verify the result from "<IVR_check_query>" on Schema "DIGITAL_CHANNEL_SEC"
	And verify the result from "<PARAM_CHANNEL_ID_query>" on Schema "DIGITAL_CHANNEL_SEC"
	And verify the result from "<ENABLE_PSD_require_query>" on Schema "DIGITAL_CHANNEL_SEC"
	And verify the result from "<ENABLE_PSD_check_query>" on Schema "DIGITAL_CHANNEL_SEC"
	And I have given "<Login_id>" on "Login_UserId"
	And I have given "<login_pass>" on "Login_Password"
	And  I am performing on "Login_SignIn_Button"
	#And I am clicking on keyword "Signup_FeedbackOptionHBL" with value "<feedback_type>"
	#And I have given "<feedback_option>" on "Signup_FeedbackText"
	#And I am performing on "Signup_FeedbackSubmit"
	#And verify through "Thank you for letting us know." on "Signup_FeedbackMessage"
	#And I am performing on "Signup_FeedbackOkBtn"
	And I am clicking on "Signup_SkipBtn"
	And verify through "Welcome" on "Login_Success_Text"
	And verify the result from "<Last_login_query>" on Schema "DIGITAL_CHANNEL_SEC"
	#And verify through "<Credit_card_no>" on "Pay_Acc_No_CC"

	@source:Data/CreditRegistration.xlsx
	Examples:
	|Case|CNIC_D|Credit_card_no|Customer_Email|Login_id|scroll_text|OTP_Value|password_policy_query|login_pass|tran_pass|success_message|login_id_query|created_on_query|updated_on_query|Last_login_query|tran_pass_encrypted_value|transaction_password_query|customer_type|customer_type_query|IVR_require_query|IVR_check_query|PARAM_CHANNEL_ID_query|ENABLE_PSD_check_query|feedback_type|feedback_option|



#
#@Registration
#Scenario Outline: 2 As a user i want to Signup using Credit Card
#	Given the test case title is "<Case>"
#	And I set value in context from data "<scroll_text>" as "scroll_text"
#	And the user is arrive to Internet Banking home page 
#	And I am clicking on "Signup_registerBtn"
#	And I am clicking on "Signup_CreditCardNav"
#	And verify through "<credit_req_text1>" on "Signup_CreditReqText1"
#	And verify through "<credit_req_text2>" on "Signup_CreditReqText2"
#	And verify through "<credit_req_text3>" on "Signup_CreditReqText3"
#	And I am clicking on "Signup_Credit_NextBtn"
#	When I scroll to element "Signup_Scroll"
#	And I am performing on "Signup_AcceptBtn"
#	And verify DVL setting through database on "<dvl_query>" on Schema "DIGITAL_CHANNEL_SEC" with date of birth "<dob>" on keyword "Signup_DOB"
#	And I have given "<CNIC_C>" on "Signup_CNIC"
#	And I have given "<credit_card_no>" on "Signup_CardNo"
#	And I have given "<email>" on "Signup_Email"
#	And I have given "<Login_id>" on "Signup_LoginId"
#	And I am performing on "Signup_ContinueBtn"
#	And verify through "<Login_id>" on "Signup_LoginIdTextVerf"
#	And verify through "<success_message1>" on "Signup_SuccessMessage1"
#	And verify through "<success_message2>" on "Signup_SuccessMessage2"
#	And verify through "<success_message3>" on "Signup_SuccessMessage3"
#	And I am performing on "Signup_SuccessNextBtn"
#	And verify the result from "<created_on_query>" on Schema "DIGITAL_CHANNEL_SEC"
#	And verify the result from "<updated_on_query>" on Schema "DIGITAL_CHANNEL_SEC"
#	And verify the result from "<last_login_query>" on Schema "DIGITAL_CHANNEL_SEC"
#	And verify the result from "<transaction_password_query>" on Schema "DIGITAL_CHANNEL_SEC"
#	And verify the message "<customer_type>" through database on "<customer_type_query>" on Schema "DIGITAL_CHANNEL_SEC"
#	And verify the result from "<IVR_require_query>" on Schema "DIGITAL_CHANNEL_SEC"
#	And verify the result from "<IVR_check_query>" on Schema "DIGITAL_CHANNEL_SEC"
#	And verify the result from "<PARAM_CHANNEL_ID_query>" on Schema "DIGITAL_CHANNEL_SEC"
#	And verify the result from "<ENABLE_PSD_require_query>" on Schema "<DIGITAL_CHANNEL_SEC>"
#	And verify the result from "<ENABLE_PSD_check_query>" on Schema "<DIGITAL_CHANNEL_SEC>"
#	And update the data by query "<password_query>" on DIGITAL_CHANNEL_SEC
#	Then I have given "<Login_id>" on "Login_UserId"
#	And I have given "<activation_password>" on "Login_Password"
#	And  I am performing on "Login_SignIn_Button"
#	And verify the result from "<password_policy_query>" on Schema "DIGITAL_CHANNEL_SEC"
#	And verify through "Signup_PassPolicy" on "Signup_PassPolicy"
#	Then I have given "<new_password>" on "Signup_ReLoginPassword"
#	And I have given "<new_password>" on "Signup_ReLoginPassword"
#	And I have given "<activation_password>" on "Signup_TransactionPassword"
#	And I have given "<activation_password>" on "Signup_ReTransactionPassword"
#	And I am performing on "Signup_SubmitBtn"
#	And verify through "<success_message>" on "Signup_PaswwordText"
#	And I am performing on "Signup_PaswwordOkBtn"
#	And verify the result from "<last_login_query>" on Schema "DIGITAL_CHANNEL_SEC"
#	And verify the message "<Login_id>" through database on "<login_id_query>" on Schema "DIGITAL_CHANNEL_SEC"
#	And verify the result from "<transaction_password_query>" on Schema "DIGITAL_CHANNEL_SEC"
#	And verify the result from "<password_change_req_query>" on Schema "DIGITAL_CHANNEL_SEC"
#	Then I have given "<Login_id>" on "Login_UserId"
#	And I have given "<new_password>" on "Login_Password"
#	And  I am performing on "Login_SignIn_Button"
#	And I wait 2000
#	And I am clicking on keyword "Signup_FeedbackOptionHBL" with value "<feedback_type>"
#	And I have given "<feedback_option>" on "Signup_FeedbackText"
#	And I am performing on "Signup_FeedbackSubmit"
#	And verify through "Thank you for letting us know." on "Signup_FeedbackMessage"
#	And I am performing on "Signup_FeedbackOkBtn"
#	Then verify through "Welcome" on "Login_Success_Text"
#
#	@source:Data/CreditRegistration.xlsx
#	Examples:
#	|Case|CNIC_C|credit_card_no|email|dob|Login_id|scroll_text|activation_password|password_query|new_password|success_message|account_query|feedback_type|feedback_option|password_change_req_query|transaction_password_query|customer_type|customer_type_query|success_message1|success_message2|success_message3|login_id_query|credit_req_text1|credit_req_text2|credit_req_text3|dvl_query|IVR_require_query|IVR_check_query|last_login_query|created_on_query|updated_on_query|PARAM_CHANNEL_ID_query|ENABLE_PSD_require_query|ENABLE_PSD_check_query|password_policy_query|

