// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace HBLAutomationAndroid.Resources.Feature.HBLMobile
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class MutualFundFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
#line 1 "MutualFund.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "MutualFund", "\tIn order to avoid silly mistakes\r\n\tAs a math idiot\r\n\tI want to be told the sum o" +
                    "f two numbers", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "MutualFund")))
            {
                global::HBLAutomationAndroid.Resources.Feature.HBLMobile.MutualFundFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(TestContext);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void WhenUserTryToLoginMobileBankingForMutualFund(string @case, string status_Query, string login_UserId_Value, string login_Password_Value, string cnic_Query, string oTP_Value, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "mytag"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When user try to login mobile banking for mutual fund", @__tags);
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given(string.Format("the test case title is \"{0}\"", @case), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
 testRunner.And(string.Format("update the data by query \"{0}\" on DIGITAL_CHANNEL_SEC", status_Query), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
 testRunner.And("the user is arrive to Mobile Banking home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.When(string.Format("I have given \"{0}\" on \"Login_UserId\"", login_UserId_Value), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 12
 testRunner.And(string.Format("I have given \"{0}\" on \"Login_Password\"", login_Password_Value), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
 testRunner.And("I wait 2000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
 testRunner.And("I am performing on \"Login_SignIn_Button\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
 testRunner.And(string.Format("I set value in context from data \"{0}\" as \"username\"", login_UserId_Value), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 16
 testRunner.And("I wait 30000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
 testRunner.And(string.Format("I have given \"{0}\" on \"Login_OTP_field\"", oTP_Value), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
 testRunner.And("I am clicking on \"Login_OTP_Verify_Button\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 19
 testRunner.And("I wait 5000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("When user try to login mobile banking for mutual fund: When user id and password " +
            "are valid BASIT555")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "MutualFund")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("source:Data/HBLMobileMutualFundLogin.xlsx")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "When user id and password are valid BASIT555")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Case", "When user id and password are valid BASIT555")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Status_query", "BEGIN UPDATE DC_REGISTERED_DEVICES RD SET RD.IS_ACTIVE = 0 WHERE RD.CUSTOMER_INFO" +
            "_ID=(SELECT CI.CUSTOMER_INFO_ID FROM DC_CUSTOMER_INFO CI WHERE CI.CUSTOMER_NAME " +
            "= \'BASIT555\') AND RD.DEVICE_OS=\'Android\';COMMIT;END;")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Login_UserId_Value", "BASIT555")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Login_Password_Value", "pakistan1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Cnic_query", "12345678")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:OTP_Value", "")]
        public virtual void WhenUserTryToLoginMobileBankingForMutualFund_WhenUserIdAndPasswordAreValidBASIT555()
        {
#line 7
this.WhenUserTryToLoginMobileBankingForMutualFund("When user id and password are valid BASIT555", "BEGIN UPDATE DC_REGISTERED_DEVICES RD SET RD.IS_ACTIVE = 0 WHERE RD.CUSTOMER_INFO" +
                    "_ID=(SELECT CI.CUSTOMER_INFO_ID FROM DC_CUSTOMER_INFO CI WHERE CI.CUSTOMER_NAME " +
                    "= \'BASIT555\') AND RD.DEVICE_OS=\'Android\';COMMIT;END;", "BASIT555", "pakistan1", "12345678", "", new string[] {
                        "source:Data/HBLMobileMutualFundLogin.xlsx"});
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("When user try to login mobile banking for mutual fund: When user id and password " +
            "are valid ALIIMRAN7")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "MutualFund")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("source:Data/HBLMobileMutualFundLogin.xlsx")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "When user id and password are valid ALIIMRAN7")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Case", "When user id and password are valid ALIIMRAN7")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Status_query", "BEGIN UPDATE DC_REGISTERED_DEVICES RD SET RD.IS_ACTIVE = 0 WHERE RD.CUSTOMER_INFO" +
            "_ID=(SELECT CI.CUSTOMER_INFO_ID FROM DC_CUSTOMER_INFO CI WHERE CI.CUSTOMER_NAME " +
            "= \'ALIIMRAN7\') AND RD.DEVICE_OS=\'Android\';COMMIT;END;")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Login_UserId_Value", "ALIIMRAN7")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Login_Password_Value", "pakistan1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Cnic_query", "12345678")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:OTP_Value", "")]
        public virtual void WhenUserTryToLoginMobileBankingForMutualFund_WhenUserIdAndPasswordAreValidALIIMRAN7()
        {
#line 7
this.WhenUserTryToLoginMobileBankingForMutualFund("When user id and password are valid ALIIMRAN7", "BEGIN UPDATE DC_REGISTERED_DEVICES RD SET RD.IS_ACTIVE = 0 WHERE RD.CUSTOMER_INFO" +
                    "_ID=(SELECT CI.CUSTOMER_INFO_ID FROM DC_CUSTOMER_INFO CI WHERE CI.CUSTOMER_NAME " +
                    "= \'ALIIMRAN7\') AND RD.DEVICE_OS=\'Android\';COMMIT;END;", "ALIIMRAN7", "pakistan1", "12345678", "", new string[] {
                        "source:Data/HBLMobileMutualFundLogin.xlsx"});
#line hidden
        }
        
        public virtual void WhenUserTryToMutualFund(
                    string @case, 
                    string cust_Profile_Id_Query, 
                    string category_Value, 
                    string fund_Names_Query, 
                    string statement_Counter, 
                    string mutual_Fund_Value, 
                    string account_No, 
                    string folio_No_Query, 
                    string folio_No, 
                    string amount_Value, 
                    string gl_Account_Query, 
                    string tran_Timing_Query, 
                    string tran_Pass_Value, 
                    string success_Message, 
                    string gUID_Query, 
                    string tran_Type_Query, 
                    string tran_Amount_Query, 
                    string from_Account_Query, 
                    string to_Account_Query, 
                    string fund_Name_Query, 
                    string disclaimer_Message, 
                    string disclaimer_Query, 
                    string db_Val, 
                    string db_Val2, 
                    string db_Val3, 
                    string db_Val4, 
                    string folio_No_Verify_Query, 
                    string customer_Name_Verify_Query, 
                    string customer_Cnic_Verify_Query, 
                    string customer_Mobile_No_Query, 
                    string tran_Amount_Verify_Query, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "mytag"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When user try to mutual fund", @__tags);
#line 26
this.ScenarioSetup(scenarioInfo);
#line 27
 testRunner.Given(string.Format("the test case title is \"{0}\"", @case), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 28
 testRunner.And("the user is arrive to Mobile Banking home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 29
 testRunner.And("I am clicking on \"Dashboard\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 30
 testRunner.And("I wait 4000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 31
 testRunner.And("I set value in context from data \"1\" as \"mutual_fund_flag\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 32
 testRunner.When("I save Account Balances", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 33
 testRunner.And(string.Format("I set value in context from data \"{0}\" as \"MutualFundName\"", mutual_Fund_Value), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 34
 testRunner.And(string.Format("I set value in context from database \"{0}\" as \"mutual_fund_disclaimer_popup\" on S" +
                        "chema \"{1}\"", disclaimer_Query, db_Val3), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 35
 testRunner.And(string.Format("I set value in context from database \"{0}\" as \"customer_profile_id\" on Schema \"{1" +
                        "}\"", cust_Profile_Id_Query, db_Val3), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 36
 testRunner.And("I am clicking on \"Dashboard_More\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 37
 testRunner.And(string.Format("I have given \"{0}\" on \"SendMoney_SearchBeneField\"", category_Value), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 38
 testRunner.And("I am clicking on \"BillPayment_CategoryLink\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 39
 testRunner.And(string.Format("I verify user Mutual Fund status on schema \"{0}\" as \"{1}\"", db_Val3, statement_Counter), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 40
 testRunner.And("I am clicking on \"MutualFund_Investment_Tab\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 41
 testRunner.And("I set list of elements from scroll view on \"MutualFund_List_FundName\" as \"3\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 42
 testRunner.And(string.Format("verify the list using \"{0}\" on Schema \"QAT_AMC\"", fund_Names_Query), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 43
 testRunner.And(string.Format("I scroll to element text as \"{0}\"", mutual_Fund_Value), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 44
 testRunner.And("I am clicking on \"MutualFund_InvestBtn\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 45
 testRunner.And(string.Format("verify through \"{0}\" on \"MutualFund_DisPopup\"", disclaimer_Message), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 46
 testRunner.And("I am clicking on \"MutualFund_PopupBtn\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 47
 testRunner.And(string.Format("I select \"{0}\" on \"MutualFund_FromAccount\"", account_No), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 48
 testRunner.And(string.Format("I check values of combobox using database from \"{0}\" on schema {1} on combobox \"M" +
                        "utualFund_FolioNumber\" of list \"MutualFund_FolioNumber_List_Locator\"", folio_No_Query, db_Val3), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 49
 testRunner.And(string.Format("I select \"{0}\" on \"MutualFund_FolioNumber\"", folio_No), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 50
 testRunner.And(string.Format("I have given \"{0}\" on \"MutualFund_FundAmount\"", amount_Value), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 51
 testRunner.And(string.Format("verify through database on \"{0}\" on Schema \"{1}\" on \"MutualFund_FundAccNo\"", gl_Account_Query, db_Val3), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 53
 testRunner.And("I am clicking on \"MutualFund_NextBtn\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 54
 testRunner.And("I wait 10000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 55
 testRunner.And("I scroll to element text as \"and risks involved\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 56
 testRunner.And("I am clicking on \"MutualFund_AgreeBtn\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 57
 testRunner.And(string.Format("verify through database on \"{0}\" on Schema \"{1}\" on \"MutualFund_CutOff_Timings\"", tran_Timing_Query, db_Val3), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 58
 testRunner.And(string.Format("I have given \"{0}\" on \"SendMoney_TranPass\"", tran_Pass_Value), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 59
 testRunner.And("I am clicking on \"MutualFund_NextBtn\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 60
 testRunner.And("I wait 5000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 61
 testRunner.And("I am clicking on \"SendMoney_Rating\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 64
 testRunner.Then(string.Format("verify through \"{0}\" on \"SendMoney_TranSuccessMessage\"", success_Message), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 66
 testRunner.And(string.Format("I set value in context from database \"{0}\" as \"GUID\" on Schema \"{1}\"", gUID_Query, db_Val), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 68
 testRunner.And(string.Format("verify through database on \"{0}\" on Schema \"{1}\" on \"TermDeposit_TranAmount\"", tran_Amount_Query, db_Val), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 69
 testRunner.And(string.Format("verify through database on \"{0}\" on Schema \"{1}\" on \"SendMoney_TranFromAcc\"", from_Account_Query, db_Val), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 70
 testRunner.And(string.Format("verify through database on \"{0}\" on Schema \"{1}\" on \"MutualFund_TranToAcc\"", to_Account_Query, db_Val), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 71
 testRunner.And(string.Format("verify through database on \"{0}\" on Schema \"{1}\" on \"MutualFund_Tran_FundName\"", fund_Name_Query, db_Val), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 72
 testRunner.And(string.Format("verify the message \"{0}\" through database on \"{1}\" on Schema \"{2}\"", folio_No, folio_No_Verify_Query, db_Val3), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 74
 testRunner.And(string.Format("verify the data using \"{0}\" on Schema \"{1}\"", customer_Cnic_Verify_Query, db_Val3), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 76
 testRunner.And(string.Format("verify the message \"{0}\" through database on \"{1}\" on Schema \"{2}\"", amount_Value, tran_Amount_Verify_Query, db_Val3), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 77
 testRunner.And("I save Transaction Info", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 78
 testRunner.And("I am clicking on \"TermDeposit_CloseBtn\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 79
 testRunner.And("I wait 3000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 80
 testRunner.And("I am clicking on \"Dashboard\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 81
 testRunner.And("I wait 2000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("When user try to mutual fund: When user try to invest in mutual fund")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "MutualFund")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("source:Data/MutualFund.xlsx")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "When user try to invest in mutual fund")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Case", "When user try to invest in mutual fund")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:cust_profile_id_query", "SELECT CUSTOMER_PROFILE_ID FROM AMC_CUSTOMER_PROFILE L WHERE L.CNIC=\'{customer_cn" +
            "ic}\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Category_Value", "Mutual Fund")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Fund_Names_query", "SELECT PP.NAME_OF_FUND from QAT_AMC.AMC_PRODUCT_PROFILE PP INNER JOIN QAT_AMC.AMC" +
            "_PRODUCT_CHANNEL PC ON PP.PRODUCT_ID = PC.PRODUCT_ID WHERE PP.IS_DELETED=0 AND P" +
            "C.IS_ENABLED = 1 AND PC.CHANNEL_CODE = \'MB\' ORDER BY (PP.NAME_OF_FUND)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:statement_counter", "all")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Mutual_Fund_Value", "HBL Equity Fund")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:account_no", "24460094903010")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:folio_no_query", "SELECT CP.FOLIO_NO FROM AMC_CUSTOMER_PROFILE CP WHERE CP.CNIC = \'{customer_cnic}\'" +
            "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:folio_no", "10437")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:amount_value", "1000")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:gl_account_query", "SELECT PP.GL_ACCOUNT_NO FROM QAT_AMC.AMC_PRODUCT_CHANNEL PP INNER JOIN AMC_PRODUC" +
            "T_PROFILE CP ON PP.PRODUCT_ID = CP.PRODUCT_ID where CP.NAME_OF_FUND =\'{mutual_fu" +
            "nd_name}\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:tran_timing_query", "Select CUT_OFF_TIME from AMC_PRODUCT_PROFILE PP where PP.NAME_OF_FUND = \'{mutual_" +
            "fund_name}\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:tran_pass_value", "pakistan2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Success_Message", "You have successfully invested in HBL Mutual Funds, for further assistance, pleas" +
            "e call HBL PhoneBanking on 021 - 111 - 111 - 425")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:GUID_query", "SELECT TT.HOST_REFERENCE_NO FROM DC_TRANSACTION TT WHERE TT.TRANSACTION_ID = \'{TR" +
            "AN_ID}\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:tran_type_query", "SELECT AC.DESCRIPTION FROM DC_TRANSACTION_ACTIVITY_CONFIG AC WHERE AC.TRANSACTION" +
            "_TYPE_ID =(SELECT DT.TRANSACTION_TYPE_ID FROM DC_TRANSACTION DT WHERE DT.TRANSAC" +
            "TION_ID = \'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:tran_amount_query", "Select TRANSACTION_AMOUNT FROM DC_TRANSACTION DT WHERE DT.CHANNEL_ID=\'1\'and  DT.T" +
            "RANSACTION_ID = \'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:from_account_query", "SELECT DT.FROM_ACCOUNT FROM DC_TRANSACTION DT WHERE DT.TRANSACTION_ID = \'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:to_account_query", "SELECT DT.TO_ACCOUNT FROM DC_TRANSACTION DT WHERE DT.TRANSACTION_ID = \'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:fund_name_query", "Select PRODUCT_CODE FROM DC_TRANSACTION DT WHERE DT.CHANNEL_ID=\'1\'and  DT.TRANSAC" +
            "TION_ID = \'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:disclaimer_message", @"Disclaimer: You have chosen to invest in Equity Related Scheme (High Risk Category). Your risk profile does not warrant you to invest in Equity Related Scheme. Kindly press ""Next"" to acknowledge that you understand the risk associated with this investment.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:disclaimer_query", "Select length(PP.POPUP_DISCLAIMER) from AMC_PRODUCT_PROFILE PP where PP.NAME_OF_F" +
            "UND = \'{mutual_fund_name}\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:db_val", "DIGITAL_CHANNEL_SEC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:db_val2", "QAT_BPS")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:db_val3", "QAT_AMC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:db_val4", "QAT_TPE")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:folio_no_verify_query", "SELECT TT.FOLIO_NO FROM QAT_AMC.AMC_TRANSACTION TT WHERE TT.GUID=\'{GUID}\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:customer_name_verify_query", "SELECT TT.CUSTOMER_NAME FROM QAT_AMC.AMC_TRANSACTION TT WHERE TT.GUID=\'{GUID}\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:customer_cnic_verify_query", "SELECT TT.CUSTOMER_CNIC FROM QAT_AMC.AMC_TRANSACTION TT WHERE TT.GUID=\'{GUID}\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:customer_mobile_no_query", "SELECT TT.CUSTOMER_MOBILE_NO FROM QAT_AMC.AMC_TRANSACTION TT WHERE TT.GUID=\'{GUID" +
            "}\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:tran_amount_verify_query", "SELECT TT.TRAN_AMOUNT FROM QAT_AMC.AMC_TRANSACTION TT WHERE TT.GUID=\'{GUID}\'")]
        public virtual void WhenUserTryToMutualFund_WhenUserTryToInvestInMutualFund()
        {
#line 26
this.WhenUserTryToMutualFund("When user try to invest in mutual fund", "SELECT CUSTOMER_PROFILE_ID FROM AMC_CUSTOMER_PROFILE L WHERE L.CNIC=\'{customer_cn" +
                    "ic}\'", "Mutual Fund", "SELECT PP.NAME_OF_FUND from QAT_AMC.AMC_PRODUCT_PROFILE PP INNER JOIN QAT_AMC.AMC" +
                    "_PRODUCT_CHANNEL PC ON PP.PRODUCT_ID = PC.PRODUCT_ID WHERE PP.IS_DELETED=0 AND P" +
                    "C.IS_ENABLED = 1 AND PC.CHANNEL_CODE = \'MB\' ORDER BY (PP.NAME_OF_FUND)", "all", "HBL Equity Fund", "24460094903010", "SELECT CP.FOLIO_NO FROM AMC_CUSTOMER_PROFILE CP WHERE CP.CNIC = \'{customer_cnic}\'" +
                    "", "10437", "1000", "SELECT PP.GL_ACCOUNT_NO FROM QAT_AMC.AMC_PRODUCT_CHANNEL PP INNER JOIN AMC_PRODUC" +
                    "T_PROFILE CP ON PP.PRODUCT_ID = CP.PRODUCT_ID where CP.NAME_OF_FUND =\'{mutual_fu" +
                    "nd_name}\'", "Select CUT_OFF_TIME from AMC_PRODUCT_PROFILE PP where PP.NAME_OF_FUND = \'{mutual_" +
                    "fund_name}\'", "pakistan2", "You have successfully invested in HBL Mutual Funds, for further assistance, pleas" +
                    "e call HBL PhoneBanking on 021 - 111 - 111 - 425", "SELECT TT.HOST_REFERENCE_NO FROM DC_TRANSACTION TT WHERE TT.TRANSACTION_ID = \'{TR" +
                    "AN_ID}\'", "SELECT AC.DESCRIPTION FROM DC_TRANSACTION_ACTIVITY_CONFIG AC WHERE AC.TRANSACTION" +
                    "_TYPE_ID =(SELECT DT.TRANSACTION_TYPE_ID FROM DC_TRANSACTION DT WHERE DT.TRANSAC" +
                    "TION_ID = \'", "Select TRANSACTION_AMOUNT FROM DC_TRANSACTION DT WHERE DT.CHANNEL_ID=\'1\'and  DT.T" +
                    "RANSACTION_ID = \'", "SELECT DT.FROM_ACCOUNT FROM DC_TRANSACTION DT WHERE DT.TRANSACTION_ID = \'", "SELECT DT.TO_ACCOUNT FROM DC_TRANSACTION DT WHERE DT.TRANSACTION_ID = \'", "Select PRODUCT_CODE FROM DC_TRANSACTION DT WHERE DT.CHANNEL_ID=\'1\'and  DT.TRANSAC" +
                    "TION_ID = \'", @"Disclaimer: You have chosen to invest in Equity Related Scheme (High Risk Category). Your risk profile does not warrant you to invest in Equity Related Scheme. Kindly press ""Next"" to acknowledge that you understand the risk associated with this investment.", "Select length(PP.POPUP_DISCLAIMER) from AMC_PRODUCT_PROFILE PP where PP.NAME_OF_F" +
                    "UND = \'{mutual_fund_name}\'", "DIGITAL_CHANNEL_SEC", "QAT_BPS", "QAT_AMC", "QAT_TPE", "SELECT TT.FOLIO_NO FROM QAT_AMC.AMC_TRANSACTION TT WHERE TT.GUID=\'{GUID}\'", "SELECT TT.CUSTOMER_NAME FROM QAT_AMC.AMC_TRANSACTION TT WHERE TT.GUID=\'{GUID}\'", "SELECT TT.CUSTOMER_CNIC FROM QAT_AMC.AMC_TRANSACTION TT WHERE TT.GUID=\'{GUID}\'", "SELECT TT.CUSTOMER_MOBILE_NO FROM QAT_AMC.AMC_TRANSACTION TT WHERE TT.GUID=\'{GUID" +
                    "}\'", "SELECT TT.TRAN_AMOUNT FROM QAT_AMC.AMC_TRANSACTION TT WHERE TT.GUID=\'{GUID}\'", new string[] {
                        "source:Data/MutualFund.xlsx"});
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("When user try to mutual fund: When user try to invest in mutual fund (AbBY Case T" +
            "wo)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "MutualFund")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("source:Data/MutualFund.xlsx")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "When user try to invest in mutual fund (AbBY Case Two)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Case", "When user try to invest in mutual fund (AbBY Case Two)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:cust_profile_id_query", "SELECT CUSTOMER_PROFILE_ID FROM AMC_CUSTOMER_PROFILE L WHERE L.CNIC=\'{customer_cn" +
            "ic}\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Category_Value", "Mutual Fund")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Fund_Names_query", "SELECT PP.NAME_OF_FUND from QAT_AMC.AMC_PRODUCT_PROFILE PP INNER JOIN QAT_AMC.AMC" +
            "_PRODUCT_CHANNEL PC ON PP.PRODUCT_ID = PC.PRODUCT_ID WHERE PP.IS_DELETED=0 AND P" +
            "C.IS_ENABLED = 1 AND PC.CHANNEL_CODE = \'MB\' ORDER BY (PP.NAME_OF_FUND)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:statement_counter", "all")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Mutual_Fund_Value", "HBL Cash Fund")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:account_no", "24460094903010")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:folio_no_query", "SELECT CP.FOLIO_NO FROM AMC_CUSTOMER_PROFILE CP WHERE CP.CNIC = \'{customer_cnic}\'" +
            "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:folio_no", "10437")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:amount_value", "2000")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:gl_account_query", "SELECT PP.GL_ACCOUNT_NO FROM QAT_AMC.AMC_PRODUCT_CHANNEL PP INNER JOIN AMC_PRODUC" +
            "T_PROFILE CP ON PP.PRODUCT_ID = CP.PRODUCT_ID where CP.NAME_OF_FUND =\'{mutual_fu" +
            "nd_name}\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:tran_timing_query", "Select CUT_OFF_TIME from AMC_PRODUCT_PROFILE PP where PP.NAME_OF_FUND = \'{mutual_" +
            "fund_name}\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:tran_pass_value", "pakistan2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Success_Message", "You have successfully invested in HBL Mutual Funds, for further assistance, pleas" +
            "e call HBL PhoneBanking on 021 - 111 - 111 - 425")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:GUID_query", "SELECT TT.HOST_REFERENCE_NO FROM DC_TRANSACTION TT WHERE TT.TRANSACTION_ID = \'{TR" +
            "AN_ID}\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:tran_type_query", "SELECT AC.DESCRIPTION FROM DC_TRANSACTION_ACTIVITY_CONFIG AC WHERE AC.TRANSACTION" +
            "_TYPE_ID =(SELECT DT.TRANSACTION_TYPE_ID FROM DC_TRANSACTION DT WHERE DT.TRANSAC" +
            "TION_ID = \'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:tran_amount_query", "Select TRANSACTION_AMOUNT FROM DC_TRANSACTION DT WHERE DT.CHANNEL_ID=\'1\'and  DT.T" +
            "RANSACTION_ID = \'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:from_account_query", "SELECT DT.FROM_ACCOUNT FROM DC_TRANSACTION DT WHERE DT.TRANSACTION_ID = \'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:to_account_query", "SELECT DT.TO_ACCOUNT FROM DC_TRANSACTION DT WHERE DT.TRANSACTION_ID = \'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:fund_name_query", "Select PRODUCT_CODE FROM DC_TRANSACTION DT WHERE DT.CHANNEL_ID=\'1\'and  DT.TRANSAC" +
            "TION_ID = \'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:disclaimer_message", @"Disclaimer: You have chosen to invest in Equity Related Scheme (High Risk Category). Your risk profile does not warrant you to invest in Equity Related Scheme. Kindly press ""Next"" to acknowledge that you understand the risk associated with this investment.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:disclaimer_query", "Select length(PP.POPUP_DISCLAIMER) from AMC_PRODUCT_PROFILE PP where PP.NAME_OF_F" +
            "UND = \'{mutual_fund_name}\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:db_val", "DIGITAL_CHANNEL_SEC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:db_val2", "QAT_BPS")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:db_val3", "QAT_AMC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:db_val4", "QAT_TPE")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:folio_no_verify_query", "SELECT TT.FOLIO_NO FROM QAT_AMC.AMC_TRANSACTION TT WHERE TT.GUID=\'{GUID}\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:customer_name_verify_query", "SELECT TT.CUSTOMER_NAME FROM QAT_AMC.AMC_TRANSACTION TT WHERE TT.GUID=\'{GUID}\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:customer_cnic_verify_query", "SELECT TT.CUSTOMER_CNIC FROM QAT_AMC.AMC_TRANSACTION TT WHERE TT.GUID=\'{GUID}\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:customer_mobile_no_query", "SELECT TT.CUSTOMER_MOBILE_NO FROM QAT_AMC.AMC_TRANSACTION TT WHERE TT.GUID=\'{GUID" +
            "}\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:tran_amount_verify_query", "SELECT TT.TRAN_AMOUNT FROM QAT_AMC.AMC_TRANSACTION TT WHERE TT.GUID=\'{GUID}\'")]
        public virtual void WhenUserTryToMutualFund_WhenUserTryToInvestInMutualFundAbBYCaseTwo()
        {
#line 26
this.WhenUserTryToMutualFund("When user try to invest in mutual fund (AbBY Case Two)", "SELECT CUSTOMER_PROFILE_ID FROM AMC_CUSTOMER_PROFILE L WHERE L.CNIC=\'{customer_cn" +
                    "ic}\'", "Mutual Fund", "SELECT PP.NAME_OF_FUND from QAT_AMC.AMC_PRODUCT_PROFILE PP INNER JOIN QAT_AMC.AMC" +
                    "_PRODUCT_CHANNEL PC ON PP.PRODUCT_ID = PC.PRODUCT_ID WHERE PP.IS_DELETED=0 AND P" +
                    "C.IS_ENABLED = 1 AND PC.CHANNEL_CODE = \'MB\' ORDER BY (PP.NAME_OF_FUND)", "all", "HBL Cash Fund", "24460094903010", "SELECT CP.FOLIO_NO FROM AMC_CUSTOMER_PROFILE CP WHERE CP.CNIC = \'{customer_cnic}\'" +
                    "", "10437", "2000", "SELECT PP.GL_ACCOUNT_NO FROM QAT_AMC.AMC_PRODUCT_CHANNEL PP INNER JOIN AMC_PRODUC" +
                    "T_PROFILE CP ON PP.PRODUCT_ID = CP.PRODUCT_ID where CP.NAME_OF_FUND =\'{mutual_fu" +
                    "nd_name}\'", "Select CUT_OFF_TIME from AMC_PRODUCT_PROFILE PP where PP.NAME_OF_FUND = \'{mutual_" +
                    "fund_name}\'", "pakistan2", "You have successfully invested in HBL Mutual Funds, for further assistance, pleas" +
                    "e call HBL PhoneBanking on 021 - 111 - 111 - 425", "SELECT TT.HOST_REFERENCE_NO FROM DC_TRANSACTION TT WHERE TT.TRANSACTION_ID = \'{TR" +
                    "AN_ID}\'", "SELECT AC.DESCRIPTION FROM DC_TRANSACTION_ACTIVITY_CONFIG AC WHERE AC.TRANSACTION" +
                    "_TYPE_ID =(SELECT DT.TRANSACTION_TYPE_ID FROM DC_TRANSACTION DT WHERE DT.TRANSAC" +
                    "TION_ID = \'", "Select TRANSACTION_AMOUNT FROM DC_TRANSACTION DT WHERE DT.CHANNEL_ID=\'1\'and  DT.T" +
                    "RANSACTION_ID = \'", "SELECT DT.FROM_ACCOUNT FROM DC_TRANSACTION DT WHERE DT.TRANSACTION_ID = \'", "SELECT DT.TO_ACCOUNT FROM DC_TRANSACTION DT WHERE DT.TRANSACTION_ID = \'", "Select PRODUCT_CODE FROM DC_TRANSACTION DT WHERE DT.CHANNEL_ID=\'1\'and  DT.TRANSAC" +
                    "TION_ID = \'", @"Disclaimer: You have chosen to invest in Equity Related Scheme (High Risk Category). Your risk profile does not warrant you to invest in Equity Related Scheme. Kindly press ""Next"" to acknowledge that you understand the risk associated with this investment.", "Select length(PP.POPUP_DISCLAIMER) from AMC_PRODUCT_PROFILE PP where PP.NAME_OF_F" +
                    "UND = \'{mutual_fund_name}\'", "DIGITAL_CHANNEL_SEC", "QAT_BPS", "QAT_AMC", "QAT_TPE", "SELECT TT.FOLIO_NO FROM QAT_AMC.AMC_TRANSACTION TT WHERE TT.GUID=\'{GUID}\'", "SELECT TT.CUSTOMER_NAME FROM QAT_AMC.AMC_TRANSACTION TT WHERE TT.GUID=\'{GUID}\'", "SELECT TT.CUSTOMER_CNIC FROM QAT_AMC.AMC_TRANSACTION TT WHERE TT.GUID=\'{GUID}\'", "SELECT TT.CUSTOMER_MOBILE_NO FROM QAT_AMC.AMC_TRANSACTION TT WHERE TT.GUID=\'{GUID" +
                    "}\'", "SELECT TT.TRAN_AMOUNT FROM QAT_AMC.AMC_TRANSACTION TT WHERE TT.GUID=\'{GUID}\'", new string[] {
                        "source:Data/MutualFund.xlsx"});
#line hidden
        }
    }
}
#pragma warning restore
#endregion

